markets/urls.py
from django.urls import path
from . import views
from .views import Index
from .views import Analytics
from .views import CandleView

app_name = "markets"

urlpatterns = [
    path("", Index.as_view(), name="index"),
    path("analytics", Analytics.as_view(), name="analytics"),
    path("batchanalysis", CandleView.as_view(), name="batchanalysis"),
    path("products", views.get_products_sublist, name="products"),
    path("ticker/<str:symbol>", views.get_ticker, name="ticker"),
    path("patterns/<str:batch>", views.get_candle_patterns, name="patterns"),
    path("addorder", views.add_candle, name="addorder"),
    path("candle/<str:symbol>", views.get_initial_chart_data, name="candle"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
]

spring_crypto_watcher/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("markets.urls")),
]

markets/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from django.utils import timezone


# Create your models here.
class User(AbstractUser):
    pass


class Product(models.Model):
    """
    Product model for providing exchange names to select from web service
    """

    title = models.CharField(max_length=255)
    exchange_id = models.CharField(max_length=50)
    created = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = "product"
        verbose_name_plural = "products"

    def __str__(self):
        return f"Product {self.title} on {self.created} with id {self.id}"


class Candle(models.Model):
    """
    Candle model for storing historical price information
    """

    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name="products"
    )
    open = models.FloatField(default=float(0))
    high = models.FloatField(default=float(0))
    low = models.FloatField(default=float(0))
    close = models.FloatField(default=float(0))
    volume = models.FloatField(default=float(0))
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="users")
    batch = models.CharField(max_length=36, default="")
    created = models.DateTimeField(default=datetime.now)

    class Meta:
        verbose_name = "candle"
        verbose_name_plural = "candles"

    def __str__(self):
        return f"Candle {self.created} with id {self.id}"

markets/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import (
    HttpResponseRedirect,
    Http404,
    HttpResponseNotFound,
    HttpResponse,
)
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.urls import reverse
from django.db import IntegrityError
from markets.models import User
from django.views import View
from django.views.decorators.csrf import csrf_exempt
from .models import Candle, Product
from markets.japanesecandles import find_japanese_patterns

import requests
import json

BINANCE_URL = "https://api.binance.us"
BINANCE_EXCH_INFO_URL = "https://api.binance.us/api/v3/exchangeInfo"


class Index(View):
    def get(self, request):
        symbol = "BTCUSD"
        candle_data = get_candle_data(BINANCE_URL, symbol=symbol, interval="1m")
        ticker = requests.get(f"{BINANCE_URL}/api/v3/ticker/24hr?symbol={symbol}")

        context = {"results": candle_data.json(), "ticker": ticker.json()}

        return render(request, "markets/index.html", context)

    def post(self, request):
        pass


class Analytics(View):
    def get(self, request):
        context = {}
        return render(request, "markets/analytics.html", context)


class CandleView(View):
    """
    CandleView displays selected saved data
    """

    def get(self, request):
        # Authenticated users view their saved candle data
        if request.user.is_authenticated:
            # Finding the unique batches found in the database
            user_batches = (
                Candle.objects.filter(user_id=request.user)
                .values_list("batch", flat=True)
                .distinct()
            )
            context = {"user_batches": user_batches}
            return render(request, "markets/candle.html", context=context)

        # Everyone else is prompted to sign in
        else:
            return HttpResponseRedirect(reverse("login"))


def get_candle_patterns(request, batch):
    """
    This method returns the row evaluations looking for candle patterns.
    :param request:
    :param batch:
    :return:
    """
    if request.method == "GET":
        candles = (
            Candle.objects.filter(batch=batch)
            .select_related()
            .values(
                "id",
                "open",
                "high",
                "low",
                "close",
                "volume",
                "created",
                "user__username",
                "product__exchange_id",
            )
        )
        df = find_japanese_patterns(candles)
        if df.shape[0] > 0:

            patterns = df.to_json(orient="records")
            return JsonResponse({"patterns": patterns})
        else:
            return JsonResponse(
                {
                    "error": "Candle patterns function find_japanese_patterns returned no records"
                }
            )


def get_ticker(request, symbol):
    """
    Retreiving 24 hour ticker data by symbol
    :param request:
    :param symbol:
    :return:
    """
    if request.method == "GET":
        ticker = requests.get(f"{BINANCE_URL}/api/v3/ticker/24hr?symbol={symbol}")
        ticker_dict = {"ticker": ticker.json()}
        return JsonResponse(ticker_dict)


def get_initial_chart_data(request, symbol):
    """
    Grabbing updated initial chart data to update a chart to new symbol
    :param request:
    :param symbol:
    :return:
    """
    if request.method == "GET":
        candle_data = get_candle_data(BINANCE_URL, symbol=symbol, interval="1m")
        candle_dict = {"candles": candle_data.json()}
        return JsonResponse(candle_dict)


@login_required
def add_candle(request):
    # Saving candle feed data to database back end
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    # Check the request body for candle messages
    data = json.loads(request.body)
    if data:
        exchange_id = data["content"]["s"]
        title = data["content"]["s"]
        batch = data["content"]["batch_id"]
        open = float(data["content"]["k"]["o"])
        close = float(data["content"]["k"]["c"])
        high = float(data["content"]["k"]["h"])
        low = float(data["content"]["k"]["l"])
        volume = float(data["content"]["k"]["v"])
        # Here we check for an instance of the Crypto currency product in the Database
        try:
            product = Product.objects.get(exchange_id=exchange_id)
        except Product.DoesNotExist:
            Product.objects.create(title=title, exchange_id=exchange_id)
            product = Product.objects.get(exchange_id=exchange_id)
        # If the product exists in the database, a Candle datapoint can be added to the DB
        if product:
            Candle.objects.create(
                batch=batch,
                product_id=product.id,
                open=open,
                high=high,
                low=low,
                close=close,
                volume=volume,
                user_id=request.user.id,
            )
    # Send response back to application
    return JsonResponse({"message": "kline added successfully."}, status=201)


def get_candle_data(url, symbol, interval="1m"):
    # General function to pull candle information from Binance
    # This function could also been done on the client side with Javascript
    # However, addition statistical data modeling can process the data with
    # Python data science libraries which may be included in the future
    candle_data = requests.get(
        f"{url}/api/v3/klines?symbol={symbol}&interval={interval}"
    )

    return candle_data


def get_products_sublist(request):
    """
    This method pulls back the sub-list of products that the application supports
    and passing them onto the client. While this code could be pulled directly
    by JavaScript, the points to demonstrate addition backend capabilities where heavy
    processing might better occur on the server side.
    :param request:
    :return:
    """
    if request.method == "GET":
        exhang_info = requests.get(f"{BINANCE_URL}/api/v3/exchangeInfo")

        symbol_dict = {}

        exchange_content = json.loads(exhang_info.content)
        symbols = exchange_content.get("symbols")
        # Here we are only interested in a subset of products
        # Therefore we limit the number of records
        for symbol in symbols[0:13]:
            symbol_code = symbol.get("symbol")
            # Some of the currencies don't chart well. While the graph displays them correctly, the
            # appears to be in error, which it isn't. These were removed due to charting issues.
            if str(symbol_code).startswith("XRP") == False and "USDTUS" not in str(
                symbol_code
            ):
                symbol_dict[symbol_code] = symbol_code

        return JsonResponse(symbol_dict)


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("markets:index"))
        else:
            return render(
                request,
                "markets/login.html",
                {"message": "Invalid username and/or password."},
            )
    else:
        return render(request, "markets/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("markets:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(
                request, "markets/register.html", {"message": "Passwords must match."}
            )

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(
                request, "markets/register.html", {"message": "Username already taken."}
            )
        login(request, user)
        return HttpResponseRedirect(reverse("markets:index"))
    else:
        return render(request, "markets/register.html")

markets/templates/markets/analytics.html
{% extends "markets/layout.html" %}
{% load static %}
{% block body %}
    <div class="row">
        <div class="col">
            <p> Select a exchange to track:
                <select id="select_cryptocurrency_01">
                    <option value="ETH-USD">ETH-USD</option>
                </select>
            </p>
        </div>
    </div>

    <div class="container">

        <div class="row">
            <div class="col">Current Buy Offer<strong>
                <div id="div_buy_price_01"></div>
            </strong></div>
            <div class="col">Current Rolling Average<strong>
                <div id="div_rolling_avg_01"></div>
            </strong></div>
        </div>
    </div>

    <div id="chart">
    </div>
    <div class="container">
        <br>
        <div class="table-responsive">
            <table id="incoming_action_table_01" class="table table-bordered table-striped">
                <tr>
                    <td>Event type: <span id="event_type"></span></td>
                    <td>Event time: <span id="event_time"></span></td>
                    <td>Symbol: <span id="symbol"></span></td>
                    <td>Price change: <span id="price_change"></span></td>
                    <td>Price change percent: <span id="price_change_percent"></span></td>

                </tr>
                <tr>
                    <td>Weighted average price: <span id="weighted_average_price"></span></td>
                    <td>First trade: <span id="first_trade"></span></td>
                    <td>Last price: <span id="last_price"></span></td>
                    <td>Last quantity: <span id="last_quantity"></span></td>
                    <td>Best bid price: <span id="best_bid_price"></span></td>
                </tr>
                <tr>
                    <td>Best bid quantity: <span id="best_bid_quatity"></span></td>
                    <td>Best ask price: <span id="best_ask_price"></span></td>
                    <td>Best ask quantity: <span id="best_ask_quantity"></span></td>
                    <td>Open price: <span id="open_price"></span></td>
                    <td>High price: <span id="high_price"></span></td>
                </tr>
                <tr>
                    <td>Low price: <span id="low_price"></span></td>
                    <td>Total traded base asset volume: <span id="total_base_asset_volume"></span></td>
                    <td>Total traded quote asset volume: <span id="total_traded_quote_asset_volume"></span></td>
                    <td>Statistics open time: <span id="statistics_open_time"></span></td>
                    <td>Statistics close time: <span id="statistics_close_time"></span></td>
                </tr>
                <tr>
                    <td>Total number of trades: <span id="total_number_of_trades"></span></td>
                </tr>
            </table>
        </div>
    </div>

    {% block script %}
        <script src="{% static 'markets/analytics.js' %}"></script>
    {% endblock %}
{% endblock %}

markets/templates/markets/candle.html
{% extends "markets/layout.html" %}
{% load static %}
{% block body %}
<h2>Pattern Discovery from Saved Data</h2>
    <div><p>It should be noted that a batch may or may not display one of the six candle patterns being searched for. The larger the sample data, the more likely a pattern match</p></div>
    <div id="analysis_table_01" class="container table-responsive p-3 my-3 border">
        <div class="row">
            <div class="col">
                {% if user_batches.count > 0 %}
                    <select name="Batches_01" id="Batches_01" size="1">
                        <option value="None">No batch selected</option>
                        {% for batch_id in user_batches %}
                            <option value="{{ batch_id }}">{{ batch_id }}</option>
                        {% endfor %}
                    </select>
                {% else %}
                    <h2>No batches saved yet</h2>
                {% endif %}

            </div>
            <div class="col">
                <br>
                <table id="table_01" class="table">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Exchange</th>
                        <th scope="col">Created</th>
                        <th scope="col">Open</th>
                        <th scope="col">High</th>
                        <th scope="col">Low</th>
                        <th scope="col">Close</th>
                        <th scope="col">Volume</th>

                        <th scope="col">Bullish Swing</th>
                        <th scope="col">Bearish Swing</th>
                        <th scope="col">Bullish Pinbar</th>
                        <th scope="col">Bearish Pinbar</th>
                        <th scope="col">Inside Bar</th>
                        <th scope="col">Outside Bar</th>
                        <th scope="col">Bullish Engulfing</th>
                        <th scope="col">Bearish Engulfing</th>
                    </tr>
                    </thead>
                    <tbody id="data_saved_analysis_01" class="table-group-divider">
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    {% block script %}
        <script src="{% static 'markets/candle.js' %}"></script>
    {% endblock %}
{% endblock %}

markets/templates/markets/index.html
{% extends "markets/layout.html" %}
{% load static %}
{% block body %}
    {% csrf_token %}
    <div class="row">
        <div class="col">
            <div><p>It should be noted that the candle chart and order book tables update from a real time feed.
                However, the data does not flow a constant rate. Pauses may occur due to market activity pauses</p>
            </div>
            <p> Select a exchange to track:
                <select id="select_cryptocurrency_01">
                    <option value="ETH-USD">ETH-USD</option>
                </select>
            </p>
        </div>
        <div class="col">
            <strong>
                <div id="recent_average">Mean: (calculating...)</div>
                <div id="current_variance">Variance: (calculating...)</div>
                <div id="current_standard_deviation">Standard Deviation: (calculating...)</div>
                {% if user.is_authenticated %}
                    <div>
                        <p>Save Candle Feed to Data Lake</p>
                        <button type="button" id="save_candle_data_01" class="btn btn-primary">Save Stream</button>
                    </div>
                    <div id="batch_message_01"></div>
                    <div id="report_transaction_id_01">
                    </div>
                {% endif %}
            </strong>
        </div>

    </div>

    <div id="chart">
    </div>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="table-responsive">
                    <table class="table table-hover" id="Ticker24hr_01">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Key</th>
                            <th scope="col">Value</th>
                        </tr>
                        </thead>
                        <tbody id="table_body_01">

                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col">
                <h2>Order Book Data</h2>
                <div>
                    <div id="current_ask_01"></div>
                    <table class="table table-hover" id="ask_table_01">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Ask</th>
                            <th scope="col">Volume</th>
                        </tr>
                        </thead>
                        <tbody id="ask_table_body_01">

                        </tbody>
                    </table>
                </div>
                <div>
                    <div id="current_bid_01"></div>
                    <table class="table table-hover" id="bid_table_01">
                        <thead class="thead-dark">
                        <tr>
                            <th scope="col">Product</th>
                            <th scope="col">Bid</th>
                            <th scope="col">Volume</th>
                        </tr>
                        </thead>
                        <tbody id="bid_table_body_01">

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {% block script %}
        {{ results|json_script:"results" }}
        {{ ticker|json_script:"ticker" }}
        <script src="{% static 'markets/index.js' %}"></script>
    {% endblock %}
{% endblock %}

markets/templates/markets/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Spring Crypto{% endblock %}</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.0.1/dist/chart.umd.min.js"></script>
<link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
  />
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Spring Crypto Watcher</a>
    <div>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'markets:index' %}"><strong>Home</strong></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'markets:analytics' %}">Analytics</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'markets:batchanalysis' %}">Batch Candle Analysis</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#"><strong>User {{ user.username }}</strong></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'markets:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'markets:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'markets:register' %}">Register</a>
                </li>
            {% endif %}

        </ul>
    </div>
</nav>
<h2>Crypto Market</h2>
<div class="body">
    {% block body %}
    {% endblock %}
</div>
</body>
</html>

markets/templates/markets/login.html
{% extends "markets/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'markets:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'markets:register' %}">Register here.</a>

{% endblock %}

markets/templates/markets/register.html
{% extends "markets/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'markets:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'markets:login' %}">Log In here.</a>

{% endblock %}